apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: race-command-center
  namespace: kdd-race
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: race-command-center
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
