export type TelemetrySample = {
  ts: number;
  session_id?: string;
  lap_id?: string;
  phase?: "braking" | "apex" | "drive";
  speed?: number;
  rpm?: number;
  gear?: number;
  tps?: number;
  brake_press_front?: number;
  brake_press_rear?: number;
  imu_roll?: number;
  imu_pitch?: number;
  imu_yaw?: number;
  susp_travel_f?: number;
  susp_travel_r?: number;
  tire_temp_surface?: number;
  tire_temp_carcass?: number;
  wheel_speed_f?: number;
  wheel_speed_r?: number;
  spin_ratio?: number;
  oil_pressure?: number;
  engine_temp?: number;
  physics_loss?: number;
  imu_drift?: number;
};
